### PR TITLE
Fix URL-Encoding in Path applied twice

### LINKED ISSUE #55: URL-Encoding in Path is applied twice
Hi,

I guess I've found a bug when trying to use a path (or the mount) with whitespaces. They seem to be encoded twice.

Example:
```rust
kv2::list(&client, "some secret engine", "some path to a secret").await.unwrap();
```

will yield the following path: https://some-vault-url.com/v1/some%2520secret%2520engine/metadata/some%2520path%2520to%2520a%2520secret

The whitespace seems to be encoded twice. First to `%20` and then the `%` is encoded to `%25` which yields `%2520`. In the end this obviously leads to a 404 on the Vault.

The same behavior can be observed on `kv2::read` etc.

Here are the relevant logs:
```
[2023-04-04T20:37:37Z DEBUG rustify::endpoint] Executing endpoint
[2023-04-04T20:37:37Z DEBUG rustify::http] Building endpoint request
[2023-04-04T20:37:37Z DEBUG vaultrs::api] Middleware: prepending v1 version to URL
[2023-04-04T20:37:37Z DEBUG vaultrs::api] Middleware: final URL is https://some-vault-url.com/v1/some%2520secret%2520engine/metadata/some%2520path%2520to%2520a%2520secret
[2023-04-04T20:37:37Z DEBUG vaultrs::api] Middleware: adding token to header
```

thanks for your work on this library.

### PR DESCRIPTION
**Pull request by darkecho731**
closes #55

### CODE REVIEW

File: src/api.rs [hunk 1]
```diff
@@ -154,7 +154,8 @@ impl MiddleWare for EndpointMiddleware {
         let mut url_c = url.clone();
         let mut segs: Vec<&str> = url.path_segments().unwrap().collect();
         segs.insert(0, self.version.as_str());
-        url_c.path_segments_mut().unwrap().clear().extend(segs);
+        url_c.set_path("");
+        url_c = url_c.join(&segs.join("/")).unwrap();
```
Comment (darkecho731) [inline src/api.rs:158]: I'm not exactly sure, if this is the smoothest way but seems to work well, as `Url::join` won't encode again.

File: src/api.rs [hunk 2]
```diff
@@ -154,7 +154,8 @@ impl MiddleWare for EndpointMiddleware {
         let mut url_c = url.clone();
         let mut segs: Vec<&str> = url.path_segments().unwrap().collect();
         segs.insert(0, self.version.as_str());
```
Comment (Haennetz) [inline src/api.rs:156]:
```suggestion
```

File: src/api.rs (hunk 1 above)
Comment (Haennetz) [inline src/api.rs:158]: In my opinion this would be a good solution for that this prevents also the duplicated path encoding.
```suggestion
        url_c.set_path(format!("{}{}", self.version, url_c.path()).as_str());
```

File: tests/kv2.rs [hunk 3]
```diff
@@ -47,6 +47,42 @@ fn test() {
...
+        let secrets = kv2::list(&client, path, "path/to/some secret/").await.unwrap();
+        assert_eq!(secrets.len(), 1);
+        assert_eq!(secrets.get(0).unwrap(), "password name with whitespace");
+
+        let res: Result<TestSecret, _> = kv2::read(&client, path, name).await;
+        assert!(res.is_ok());
+        assert_eq!(res.unwrap().key, endpoint.secret.key);
+    });
+}
+
```
Comment (Haennetz) [inline tests/kv2.rs:85]: This causes on my system an error because it tries to run two vault servers with the same port.
Please write an async function and pass the vault server to it.

**Review by Haennetz — COMMENTED** [review]
Thanks for your Fix, and sorry for the delayed review 
I think the solution I provided would be more efficient then the current implementation, because we don't need to convert the path segments in new Vec.

**Comment by Haennetz** [comment]
Also, please rebase your branch

**Comment by darkecho731** [comment]
Hi, I have implemented the proposed changes.

**Comment by Haennetz** [comment]
Thanks the fix will be included in the next release.
